category_name = "Recipes"
category_color = 0x68D080
category_description = { _ = "Recipes for all professions." }
mergeable = true
merged_by_default = true

# [alchemy]
# name = "Alchemy Recipes"
# description = { _ = "Recipes for crafting potions, elixirs, and transmuting materials." }
# color = 0x4E9A06
# items = []

[blacksmithing]
name = "Blacksmithing Recipes"
description = { _ = "Recipes for forging metal armor, weapons, and enhancements." }
color = 0x8F8F8F
items = [
    83787,
    83788,
    83789,
    83790,
    83791,
    83792,
    84158,
    84159,
    84160,
    84161,
    84162,
    84163,
    84164,
    84165,
    84166,
    84167,
    84168,
    84169,
    84170,
    84171,
    84172,
    84173,
    84196,
    84197,
    84198,
    84208,
    84217,
    84218,
    84219,
    84220,
    84221,
    84222,
    84223,
    84224,
    84225,
    84226,
    84227,
    87408,
    87409,
    87410,
    87411,
    87412,
    87413,
    90531,
    90532,
    94552,
    94567,
    94568,
    94569,
    94570,
    94571,
    94572,
    100865,
]

[enchanting]
name = "Enchanting Recipes"
description = { _ = "Recipes for enchanting gear with magical properties." }
color = 0x5C3566
items = [84557, 84559, 84561, 84580, 84583, 84584]

[engineering]
name = "Engineering Recipes"
description = { _ = "Recipes for creating gadgets, explosives, and mechanical devices." }
color = 0xC4A000
items = [89992, 89993, 89994, 89996, 89997, 100910]

# [herbalism]
# name = "Herbalism Recipes"
# description = { _ = "Recipes for gathering herbs for use in Alchemy and Inscription." }
# color = 0x4E9A06
# items = []

[inscription] # introduced in WotLK
name = "Inscription Recipes"
description = { _ = "Recipes for scribing glyphs and crafting scrolls and tomes." }
color = 0x855C33
items = [
    102534,
    104209,
    104215,
    104217,
    104219,
    104220,
    104223,
    104224,
    104226,
    104227,
    104228,
    104229,
    104230,
    104231,
    104234,
    104235,
    104245,
]

[jewelcrafting] # introduced in TBC
name = "Jewelcrafting Recipes"
description = { _ = "Recipes for cutting gems and crafting jewelry." }
color = 0xAD7FA8
items = [
    83811,
    83815,
    83825,
    83830,
    83840,
    83842,
    83844,
    83845,
    83848,
    83851,
    83859,
    83862,
    83872,
    83877,
    83901,
    83925,
    83926,
    83931,
    83932,
    90470,
    90471,
    95470,
    95471,
]

[leatherworking]
name = "Leatherworking Recipes"
description = { _ = "Recipes for crafting leather and mail armor." }
color = 0x8B4513
items = [
    86235,
    86237,
    86238,
    86240,
    86241,
    86242,
    86243,
    86244,
    86245,
    86246,
    86247,
    86248,
    86249,
    86250,
    86251,
    86252,
    86253,
    86254,
    86255,
    86256,
    86257,
    86258,
    86259,
    86260,
    86261,
    86262,
    86263,
    86264,
    86265,
    86266,
    86267,
    86268,
    86269,
    86270,
    86271,
    86272,
    86273,
    86274,
    86275,
    86276,
    86277,
    86278,
    86279,
    86280,
    86281,
    86283,
    86284,
    86295,
    86297,
    86308,
    86309,
    95467,
    95468,
    100864,
    102513,
]

# [mining]
# name = "Mining Recipes"
# description = { _ = "Recipes for extracting ores and stones." }
# color = 0x7F7F7F
# items = []

# [skinning]
# name = "Skinning Recipes"
# description = { _ = "Recipes for harvesting leather from beasts." }
# color = 0x7B3503
# items = []

[tailoring]
name = "Tailoring Recipes"
description = { _ = "Recipes for weaving cloth armor and other cloth items." }
color = 0xD3D7CF
items = [
    86352,
    86353,
    86354,
    86355,
    86356,
    86357,
    86358,
    86359,
    86360,
    86361,
    86362,
    86363,
    86364,
    86365,
    86366,
    86367,
    86368,
    86369,
    86370,
    86371,
    86375,
    86376,
    86377,
    86379,
    86380,
    86381,
    86382,
    100863,
]

[cooking]
name = "Cooking Recipes"
description = { _ = "Recipes for preparing food that provides buffs." }
color = 0xE9B96E
items = [
    74657,
    74658,
    75013,
    75017,
    85502,
    85505,
    86393,
    87266,
    101765,
    101766,
    101767,
    101768,
    101769,
    101770,
]

# [Fishing]
# name = "Fishing Recipes"
# description = { _ = "Recipes for catching fish and other underwater items." }
# color = 0x3465A4
# items = []

# [Archaeology] # introduced in Cataclysm
# name = "Archaeology Recipes"
# description = { _ = "Recipes for uncovering artifacts and historical items." }
# color = 0xC17D11
# items = []

# [First_Aid] # gone with BFA
# name = "First Aid Recipes"
# description = { _ = "Recipes for crafting bandages and anti-venoms." }
# color = 0xCC0000
# items = []
